# Generated by Django 3.1.7 on 2021-02-23 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MaterialSystem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num_elements", models.IntegerField()),
                ("num_entries", models.IntegerField()),
                ("elements", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="MLModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("train_MAE", models.FloatField()),
                ("train_MSE", models.FloatField()),
                ("test_MAE", models.FloatField()),
                ("test_MSE", models.FloatField()),
                ("baseline_MSE", models.FloatField()),
                ("baseline_MAE", models.FloatField()),
                (
                    "material_system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mlmodel.materialsystem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SVRModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parameters", models.TextField()),
                ("intercept", models.TextField()),
                ("dual_coef", models.TextField()),
                ("sparse", models.TextField()),
                ("shape_fit", models.TextField()),
                ("support", models.TextField()),
                ("support_vectors", models.TextField()),
                ("n_support", models.TextField()),
                ("probA", models.TextField()),
                ("probB", models.TextField()),
                ("gamma", models.TextField()),
                ("descriptor_parameters", models.TextField()),
                ("transformed", models.BooleanField(default=False)),
                ("scale", models.TextField(null=True)),
                ("mean", models.TextField(null=True)),
                ("var", models.TextField(null=True)),
                ("n_samples_seen", models.IntegerField(null=True)),
                (
                    "material_system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mlmodel.materialsystem",
                    ),
                ),
                (
                    "mlmodel",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mlmodel.mlmodel",
                    ),
                ),
            ],
        ),
    ]
