# Generated by Django 3.1.7 on 2021-03-17 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mlmodel", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="materialsystem",
            name="num_entries",
        ),
        migrations.AddField(
            model_name="mlmodel",
            name="DOI",
            field=models.TextField(default="l"),
            preserve_default=False,
        ),
    ]
