# Generated by Django 3.1.7 on 2021-03-17 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlmodel', '0002_auto_20210317_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlmodel',
            name='DOI',
            field=models.CharField(max_length=60),
        ),
    ]
