# Generated by Django 3.1.7 on 2021-03-05 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mlmodel', '0002_trainingdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingdata',
            name='model',
        ),
        migrations.AddField(
            model_name='trainingdata',
            name='model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='data', to='mlmodel.mlmodel'),
            preserve_default=False,
        ),
    ]
